//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaOseledchenko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        public string name { get; set; }
        public int cost { get; set; }
        public string duration { get; set; }
        public int adultOnly { get; set; }
        public int id { get; set; }
    }
}
